[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Gruvbox-Material-Dark-Soft-red
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Gruvbox-Material-Dark-Soft-red
GtkTheme=Gruvbox-Material-Dark-Soft-red
IconTheme=Gruvbox-Material-Dark-Soft-red
MetacityTheme=Gruvbox-Material-Dark-Soft-red
